version: 2

main_db:
  host: mariadb
  username: root
  password: change-me-root
  database: postal

message_db:
  host: mariadb
  username: root
  password: change-me-root
  prefix: postal

logging:
  enabled: true
  rails_log_enabled: true

rails:
  environment: production
  secret_key: CHANGE_ME_WITH_LONG_RANDOM_SECRET
